from enum import Enum


class ActivityAction(str, Enum):
    APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED"

    CONSULTATION_STARTED = "CONSULTATION_STARTED"
    CONSULTATION_COMPLETED = "CONSULTATION_COMPLETED"

    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"

    PRESCRIPTION_ISSUED = "PRESCRIPTION_ISSUED"
    PRESCRIPTION_REVISED = "PRESCRIPTION_REVISED"

    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"

    ADMIN_FORCE_CANCEL = "ADMIN_FORCE_CANCEL"