"""NoTrafficReceived means "no users", not "no monitoring".

THE BUG, MEASURED ON THE RUNNING STACK
The same middleware counts every request, including the ones the monitoring
system makes about itself. Prometheus scrapes /metrics every 15s and Docker
probes /health/live every 30s, so with zero real users:

    sum(rate(http_requests_total[10m]))                     = 0.3008...
    ... {path!~"/metrics|/health|/health/(live|ready)"}     = no data

The rule was `sum(rate(http_requests_total[10m])) == 0`. Its left side is never
zero while Prometheus is alive, so the alert for "nothing can reach the API"
could not fire under any circumstance -- including the total outage it was
written for. The only two series on the production instance at the time of
writing were /metrics (4314 requests) and /health/live (539).

TWO WAYS TO BE SILENT, NOT ONE
Filtering alone is not enough. When no real request has ever been served the
filtered selector matches no series at all, and an empty vector compared to 0 is
still empty -- so a fresh deployment receiving nothing would again alert on
nothing. That is what the absent() arm covers.

WHAT IS TESTED WHERE
The promtool unit tests in alerts_test.yml are the real proof: they push
synthetic series through the actual rule file and assert the alert fires. They
were confirmed to FAIL against the previous expression before this was written.
Because they need Docker, the structural assertions below repeat the parts that
can be checked anywhere, so CI without a daemon still catches a regression.
"""

import pathlib
import shutil
import subprocess

import pytest

from tests.monitoring import monitoring_images

yaml = pytest.importorskip("yaml")

REPO = pathlib.Path(__file__).parent.parent.parent

ALERTS = REPO / "alerts.yml"
RULE_TESTS = pathlib.Path(__file__).parent / "alerts_test.yml"

ALERT = "NoTrafficReceived"

# Counted by the middleware, generated by the monitoring system itself.
INFRASTRUCTURE_PATHS = ["/metrics", "/health", "/health/live", "/health/ready"]

# Derived from docker-compose.yml, never hard-coded: promtool answers for the
# version running it, so validating with a different one proves nothing about
# the server that will load these rules.
PROMETHEUS_IMAGE = monitoring_images.PROMETHEUS_IMAGE

docker_available = pytest.mark.skipif(
    shutil.which("docker") is None,
    reason="docker is not available in this environment",
)


@pytest.fixture(scope="module")
def rule() -> dict:
    for group in yaml.safe_load(ALERTS.read_text())["groups"]:
        for entry in group.get("rules", []):
            if entry.get("alert") == ALERT:
                return entry

    raise AssertionError(f"{ALERT} is not defined in alerts.yml")


@pytest.fixture(scope="module")
def expression(rule) -> str:
    return " ".join(rule["expr"].split())


# ---------------------------------------------------------------------------
# The rule no longer watches its own monitoring traffic
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def path_filter(expression):
    """The regex the rule filters `path` with, evaluated rather than grepped.

    PromQL anchors matchers, so re.fullmatch is the faithful equivalent. This
    tests what the selector DOES, so an equivalent rewrite of the pattern keeps
    passing and a semantic change does not.
    """
    import re

    match = re.search(r'path!~"([^"]+)"', expression)

    assert match, f"no path!~ matcher in the expression: {expression}"

    return re.compile(match.group(1))


@pytest.mark.parametrize("path", INFRASTRUCTURE_PATHS)
def test_the_rule_excludes_self_generated_traffic(path_filter, path):
    """THE REGRESSION. Each of these is produced by Prometheus or the container
    healthcheck, and counting any one of them keeps the alert permanently
    silent."""
    assert path_filter.fullmatch(path), (
        f"{path} is not excluded from {ALERT}; monitoring traffic alone would "
        "keep the alert from ever firing"
    )


def test_the_rule_excludes_unrouted_requests(path_filter):
    """Scanner noise on a public address is not application traffic."""
    assert path_filter.fullmatch("<unmatched>")


@pytest.mark.parametrize(
    "path",
    [
        "/api/appointments",
        "/api/patients/{patient_id}",
        "/health-records/{record_id}",
        "/healthcheck-report",
        "/api/health-summary",
        "/metrics-export",
        "/docs",
    ],
)
def test_real_application_routes_are_still_counted(path_filter, path):
    """The other half: over-filtering would hide traffic and re-create the bug
    from the opposite direction. `/health-records` and `/metrics-export` are the
    cases a loose prefix regex would have swallowed."""
    assert not path_filter.fullmatch(path), (
        f"{path} is treated as infrastructure traffic and no longer counts as "
        "real application traffic"
    )


def test_the_exclusion_is_a_negative_matcher(expression):
    """`!~`, not `=~`: the filter must remove those paths, not select them."""
    assert 'path!~"' in expression.replace(" ", ""), expression
    assert 'path=~"' not in expression.replace(" ", ""), (
        "the selector matches only infrastructure paths — inverted"
    )


def test_the_rule_is_not_the_unfiltered_expression(expression):
    """The exact expression that shipped broken."""
    assert expression != "sum(rate(http_requests_total[10m])) == 0"
    assert "http_requests_total{" in expression, (
        "http_requests_total is used without any label filter"
    )


def test_a_health_lookalike_route_is_not_excluded(expression):
    """`/health.*` would also exclude an application route such as
    /health-records, silently dropping real traffic from the signal. The
    alternation is spelled out so PromQL's anchoring keeps them distinct."""
    assert "/health.*" not in expression, (
        "a loose prefix would exclude application routes beginning with /health"
    )
    assert "/health/(live|ready)" in expression or "/health/live" in expression


def test_both_silent_cases_are_covered(expression):
    """`== 0` catches traffic that stops; absent() catches traffic that never
    started. Either one alone leaves a silent failure mode."""
    assert "== 0" in expression
    assert "absent(" in expression, (
        "without absent(), a deployment that never served a real request "
        "produces an empty vector and no alert"
    )


def test_the_two_arms_filter_identically(expression):
    """A filter that drifts between the arms would make absent() fire on traffic
    the == 0 arm considers real, or vice versa."""
    import re

    selectors = re.findall(r"http_requests_total\{([^}]*)\}", expression)

    assert len(selectors) == 2, f"expected two selectors, found {selectors}"
    assert selectors[0] == selectors[1], (
        f"the arms use different filters:\n  {selectors[0]}\n  {selectors[1]}"
    )


def test_the_alert_still_has_its_severity_and_annotations(rule):
    """The milestone changes what the rule measures, not how it is routed."""
    assert rule["labels"]["severity"] == "warning"
    assert rule["for"] == "15m"
    assert "summary" in rule["annotations"]
    assert "description" in rule["annotations"]


def test_no_other_rule_was_changed_to_use_the_filter():
    """Scoped: this milestone touches one rule. Error-rate and latency rules
    must keep counting every request, including health probes, or their
    denominators change meaning."""
    filtered = [
        entry["alert"]
        for group in yaml.safe_load(ALERTS.read_text())["groups"]
        for entry in group.get("rules", [])
        if "<unmatched>" in " ".join(entry["expr"].split())
    ]

    assert filtered == [ALERT], (
        f"the traffic filter leaked into other rules: {filtered}"
    )


# ---------------------------------------------------------------------------
# promtool: the rule actually fires
# ---------------------------------------------------------------------------


def test_the_rule_test_file_exists():
    assert RULE_TESTS.is_file()


def test_the_rule_tests_point_at_the_real_alert_file():
    """A unit test against a copy of the rules proves nothing about production."""
    config = yaml.safe_load(RULE_TESTS.read_text())

    referenced = [
        (RULE_TESTS.parent / name).resolve() for name in config["rule_files"]
    ]

    assert ALERTS.resolve() in referenced, referenced


def test_the_rule_tests_cover_both_silent_cases():
    config = yaml.safe_load(RULE_TESTS.read_text())

    names = [case.get("name", "") for case in config["tests"]]

    assert any("never served" in name for name in names), names
    assert any("stops" in name for name in names), names
    assert any("infrastructure" in name for name in names), names


@docker_available
def test_promtool_unit_tests_pass():
    """The real proof: synthetic series through the real rule file.

    Confirmed to fail against the previous expression -- every firing case
    returned `got:[]`.
    """
    result = subprocess.run(
        [
            "docker", "run", "--rm",
            "-v", f"{REPO}:/w:ro", "-w", "/w",
            "--entrypoint", "promtool", PROMETHEUS_IMAGE,
            "test", "rules", str(RULE_TESTS.relative_to(REPO)),
        ],
        capture_output=True, text=True, timeout=300,
    )

    if result.returncode != 0 and "Unable to find image" in result.stderr:
        pytest.skip("prometheus image is not available locally")

    assert result.returncode == 0, (
        f"promtool rule tests failed:\n{result.stdout}\n{result.stderr}"
    )
    assert "SUCCESS" in result.stdout


@docker_available
def test_the_rule_file_is_valid():
    result = subprocess.run(
        [
            "docker", "run", "--rm",
            "-v", f"{ALERTS}:/alerts.yml:ro",
            "--entrypoint", "promtool", PROMETHEUS_IMAGE,
            "check", "rules", "/alerts.yml",
        ],
        capture_output=True, text=True, timeout=300,
    )

    if result.returncode != 0 and "Unable to find image" in result.stderr:
        pytest.skip("prometheus image is not available locally")

    assert result.returncode == 0, result.stdout + result.stderr
    assert "SUCCESS" in result.stdout
