version: "3.9"

services:
  api:
    build: .
    container_name: helpdoctor_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    restart: always

  postgres:
    image: postgres:16
    container_name: helpdoctor_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: helpdoctor_redis
    ports:
      - "6379:6379"
    restart: always

  jaeger:
  
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"

  prometheus:
    image: prom/prometheus
    container_name: helpdoctor_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: helpdoctor_grafana
    ports:
      - "3000:3000"
    restart: always


volumes:
  postgres_data:



