"""add indexes to appointments

Revision ID: 1a20dc9f1e5a
Revises: f2f6f5534924
Create Date: 2026-02-21 10:49:05.305451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a20dc9f1e5a'
down_revision: Union[str, Sequence[str], None] = 'f2f6f5534924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_appointments_patient_id'),
        'appointments',
        ['patient_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_appointments_scheduled_at'),
        'appointments',
        ['scheduled_at'],
        unique=False
    )
    op.create_index(
        op.f('ix_appointments_status'),
        'appointments',
        ['status'],
        unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    
    # ### end Alembic commands ###
