"""add notifications table

Revision ID: 5815e10cf667
Revises: 7c778950404a
Create Date: 2026-01-31 11:37:43.469687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5815e10cf667'
down_revision: Union[str, Sequence[str], None] = '7c778950404a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_appointment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        ALTER TABLE appointments
        ALTER COLUMN cancelled_by TYPE INTEGER
        USING cancelled_by::integer
    """)
    op.create_foreign_key(None, 'appointments', 'users', ['cancelled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "appointments_cancelled_by_fkey",
        "appointments",
        type_="foreignkey"
    )
    op.alter_column(
        'appointments',
        'cancelled_by',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True
    )
    op.drop_table('notifications')

    # ### end Alembic commands ###
