"""Is this database the one this code expects?

Run immediately after `alembic upgrade head`, inside the same container, as part
of the `migrate` service's command:

    alembic upgrade head && python -m scripts.verify_schema

That placement is the whole design. api, celery_worker, celery_beat and
outbox_worker all declare

    depends_on: migrate: { condition: service_completed_successfully }

so compose starts none of them unless this exits 0. The gate therefore needs no
deployment script, no orchestration and no new framework — it borrows the
ordering guarantee that was already there, and works identically in production
and staging because both use the same `migrate` service.

TWO QUESTIONS, BECAUSE THEY FAIL DIFFERENTLY

Is the database AT the revision this code expects? This is the one that would
have caught staging sitting eight days behind while every container reported
healthy. A migration that never ran leaves no other trace.

Does the schema still MATCH the models? `alembic check` answers that. A revision
number is only a claim; this checks the thing the claim is about, and catches a
migration that ran but does not describe what the code now declares.

Neither subsumes the other. A data-only migration changes the revision without
changing the schema, so `check` alone would miss it; a hand-edited column
matches no revision at all, so the revision comparison alone would miss that.

IT CANNOT TARGET THE WRONG DATABASE
There is no host, port or URL argument. The revision is read through the
application's own engine, built from the settings of whichever container this
runs in, and the drift check runs through alembic/env.py, which resolves its URL
the same way. Pointing this at production requires running it in a container
configured for production, which is the only situation in which that is the
correct thing to do.
"""

import asyncio
import sys
from contextlib import suppress

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import text

from app.db.postgres import engine

ALEMBIC_INI = "alembic.ini"


def code_head() -> str | None:
    """The revision this checkout expects, read from the migration files."""
    script = ScriptDirectory.from_config(Config(ALEMBIC_INI))

    return script.get_current_head()


async def database_revision() -> str | None:
    """The revision the database records, or None if it has never been stamped.

    Read straight from alembic_version through the application's engine rather
    than by parsing `alembic current` output, which changes with logging
    settings and would need the same string handling in every caller.
    """
    async with engine.connect() as conn:
        result = await conn.execute(
            text("SELECT version_num FROM alembic_version")
        )
        row = result.first()

    return row[0] if row else None


def check_for_drift() -> None:
    """Raise if the models describe something the schema does not.

    This is `alembic check`, through its own API rather than a subprocess, so
    the failure arrives as an exception with its diff attached instead of a
    parsed exit code.
    """
    command.check(Config(ALEMBIC_INI))


def verify() -> int:
    """Synchronous on purpose.

    `alembic check` runs alembic/env.py, which drives its own event loop. Calling
    it from inside one — an `async def verify()` — nests loops and leaves asyncpg
    connections being finalised against a loop that has already closed, which
    surfaces as "Event loop is closed" noise on an otherwise successful run. So
    the one async step is run to completion first, and the alembic call happens
    outside any loop.
    """
    head = code_head()

    try:
        current = asyncio.run(_revision_and_dispose())
    except Exception as exc:
        print(f"!!! could not read the database revision: {exc}", file=sys.stderr)
        return 1

    if current != head:
        print(
            f"!!! schema out of date: database is at {current or '<unstamped>'}, "
            f"code head is {head}",
            file=sys.stderr,
        )
        print(
            "!!! the application will not be started against this database",
            file=sys.stderr,
        )
        return 1

    print(f"==> schema at {current}")

    try:
        check_for_drift()
    except Exception as exc:
        # AutogenerateDiffsDetected in the ordinary case; anything else here is
        # a broken configuration and equally disqualifying.
        print(f"!!! schema drift detected: {exc}", file=sys.stderr)
        print(
            "!!! the database does not match the models; "
            "the application will not be started",
            file=sys.stderr,
        )
        return 1

    print("==> schema verified")

    return 0


async def _revision_and_dispose() -> str | None:
    """Read the revision and release the pool, in one loop.

    Disposing in a second asyncio.run() would tear down connections created in
    the first one, which is exactly the cross-loop finalisation being avoided.
    """
    try:
        return await database_revision()
    finally:
        with suppress(Exception):
            await engine.dispose()


def main() -> int:
    return verify()


if __name__ == "__main__":
    sys.exit(main())
